name: 'Keeper Commander Secrets Valut'
description: 'A GitHub Action to consume Secrets from Keeper'
inputs:

  keeper-secret-config:
    description: 'Keeper Commander config file'
    required: true
  
  server:
    description: 'Keeper server host name (ex. keepersecurity.au) or abbreviation (ex. EU)'
    required: false

  verify-ssl-certs:
    description: 'Verify SSL certificate. Default: true'
    required: false

  secrets:
    description: 'A list of secrets to retrieve from Keeper Vault'
    required: true

runs:
  using: "composite"
  steps:

    - run: python -m pip install -r ${{ github.action_path }}/src/requirements.txt  # Installing dependencies
      shell: bash

    - name: Run Entry
      env:
        KEEPER_SERVER: ${{ inputs.keeper-server }}
        SECRET_CONFIG: ${{ inputs.keeper-secret-config }}
        VERIFY_SSL_CERTS: ${{ inputs.verify-ssl-certs }}
        SECRETS: ${{ inputs.secrets }}
      run: python ${{ github.action_path }}/src/entrypoint.py
      shell: bash

