name: 'Keeper Commander Secrets Vault'
description: 'A GitHub Action to consume secrets from Keeper'
inputs:

  keeper-secret-config:
    description: 'Keeper Commander config json'
    required: true
  
  server:
    description: 'Keeper server host name (ex. keepersecurity.au) or abbreviation (ex. EU). Default: keepersecurity.com'
    required: false
    default: 'keepersecurity.com'

  verify-ssl-certs:
    description: 'Verify SSL certificate. Default: true'
    required: false
    default: 'true'

  secrets:
    description: 'A list of secrets to retrieve from Keeper Vault'
    required: true

outputs:
  out-pwds: # id of the output
    description: 'The sum of the inputs'
    value: ${{ steps.run-entry.outputs.out-pwds }}
runs:
  using: "composite"
  steps:

    - name: Installing dependencies
      id: dependencies
      run: |
        python -V
        python3 -V
        python3 -m pip install -r ${{ github.action_path }}/requirements.txt  #
      shell: bash

    - name: Run Entry
      id: run-entry
      env:
        KEEPER_SERVER: ${{ inputs.server }}
        SECRET_CONFIG: ${{ inputs.keeper-secret-config }}
        VERIFY_SSL_CERTS: ${{ inputs.verify-ssl-certs }}
        SECRETS: ${{ inputs.secrets }}
      run: |
        python3 ${{ github.action_path }}/ghaentrypoint.py
      shell: bash
