name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: "composite"
  steps:
    - run: python -m pip install actions-toolkit keepersecuritysm  # Installing dependencies
      shell: bash
    # - run: python ${{ github.action_path }}/entrypoint.py ${{ inputs.gh_token }} ${{ inputs.file_name }} ${{ github.workspace }} ${{ inputs.max_repo_description }}
    - run: python ${{ github.action_path }}/entrypoint.py
      shell: bash
