on: 
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-secret-injection:
    runs-on: ubuntu-latest
    name: Build process
    steps:

      - name: Retrieve test secrets from Keeper
        id: zecrets
        uses: maksimu/commander-sm-action@master
        with:
          server: http://dcb97cdba043.ngrok.io
          keeper-secret-config: ${{ secrets.KEEPER_SECRET_KEY }}
          verify-ssl-certs: false
          secrets: |
            NDsdWcA5uBvKbWq4NvBC0Q password | env:SECRIT
            NDsdWcA5uBvKbWq4NvBC0Q password | out:OUT_SECRIT
#            KDjNKy8EkxYVLbnAadJvAQ file:Certificate.crt | file:~/savedfilefromkeeeper.crt


      # Use the output from the `hello` step
      - name: Print password
        run: |
          msg=$(printf '%s' ${{ steps.zecrets.outputs.out-result-map }} | jq --raw-input --slurp '.')
          echo $msg  > msg1.txt
          echo out-result-map=${{ fromJSON(steps.zecrets.outputs.out-result-map) }}
          echo ${{ fromJSON(steps.zecrets.outputs.out-result-map) }}  > msg2.txt

          echo OUT_SECRIT=[${{ fromJSON(steps.zecrets.outputs.out-result-map).OUT_SECRIT }}]

          echo "---All Outputs of 'zecrets' step"
          echo "ALL=${{ join(steps.zecrets.outputs.*, '\n') }}"

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v2
        with:
          name: msg-files
          path: msg*.txt
