on: 
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  buildexecutable:
    runs-on: ubuntu-latest
    name: Build process
    steps:

      - name: Retrieve test secrets from Keeper
        id: secrets-vars
        uses: maksimu/commander-sm-action@master
        with:
          server: http://dcb97cdba043.ngrok.io
          keeper-secret-config: ${{ secrets.KEEPER_SECRET_KEY }}
          verify-ssl-certs: false
          secrets: |
            NDsdWcA5uBvKbWq4NvBC0Q password | env:PASSWORD
            NDsdWcA5uBvKbWq4NvBC0Q password | out:OUT_PASSWORD
#            KDjNKy8EkxYVLbnAadJvAQ file:Certificate.crt | file:~/savedfilefromkeeeper.crt

      - name: Sample out vars
        id: sample-out
        run: |
          echo "::set-output name=action_fruit::strawberry"

      # Use the output from the `hello` step
      - name: Print password
        run: |
          echo "password is [${{ steps.secrets-vars.outputs.OUT_PASSWORD }}]\n"
          echo "who is [${{ steps.secrets-vars.outputs.WHO }}]\n"
          echo "All Outputs of 'secrets-vars' step\n"
          echo "${{join(steps.secrets-vars.outputs.*, '\n')}}"
          echo "All Outputs of 'sample-out' step\n"
          echo "${{join(steps.sample-out.outputs.*, '\n')}}"
          echo "Env vars\n"
          printenv
      - run: ls -la
