on: 
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-secret-injection:
    runs-on: self-hosted
    name: Build process
    steps:

      - name: Retrieve test secrets from Keeper
        id: keepersecrets
        uses: maksimu/commander-sm-action@master
        with:
          server: https://dev.keepersecurity.com
          keeper-secret-config: ${{ secrets.KEEPER_SECRET_KEY }}
          verify-ssl-certs: false
          secrets: |
            NDsdWcA5uBvKbWq4NvBC0Q password | env:SECRIT
            NDsdWcA5uBvKbWq4NvBC0Q field:login | out:Login
            NDsdWcA5uBvKbWq4NvBC0Q password | out:OUT_SECRIT2
            NDsdWcA5uBvKbWq4NvBC0Q file:mymodule.py | file:/tmp/myflie-mymodule.py
            NDsdWcA5uBvKbWq4NvBC0Q custom:passcode | env:mypasscode


      # Use the output from the `hello` step
      - name: Print 'out'
        run: |
          echo OUT_SECRIT1=[${{ fromJSON(steps.keepersecrets.outputs.out-secrets).OUT_SECRIT1 }}]
          echo "ALL=${{ join(steps.keepersecrets.outputs.*, '\n') }}"
          echo "ALL=${{ join(steps.keepersecrets.outputs.*, '\n') }}"

      - name: Print 'env'
        run: |
          echo "SECRIT=${{ env.SECRIT }}"
        shell: bash

      - name: Print 'files'
        run: |
          pwd
          cd ~
          ls -la ~
          ls -la /tmp