on: 
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  buildexecutable:
    runs-on: ubuntu-latest
    name: Build process
    steps:

      - name: Retrieve test secrets from Keeper
        id: file_retrieve_step
        uses: maksimu/commander-sm-action@master
        with:
          keeper-secret-config: ${{ secrets.KEEPER_SECRET_KEY }}
          verify-ssl-certs: false
          secrets: |
            KDjNKy8EkxYVLbnAadJvAQ password | env:PASSWORD
            KDjNKy8EkxYVLbnAadJvAQ file:Certificate.crt | file:~/savedfilefromkeeeper.crt

      # Use the output from the `hello` step
      - name: Print password
        run: echo "password is ${{ steps.file_retrieve_step.outputs.OUTPASs }}"
      - run: ls -la
